name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.9.9-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean package -B
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ./target/*.jar
          if-no-files-found: error