# .github/workflows/build.yml
name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          mvn --version
          mvn clean compile test package -B

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ./target/*.jar
          if-no-files-found: error